// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Maxi.Citizenship.Models;

public partial class Answer
{
    public int Id { get; set; }

    public DateTime CreatedOn { get; set; }

    public Guid CreatedBy { get; set; }

    public DateTime LastModifiedOn { get; set; }

    public Guid LastModifiedBy { get; set; }

    public short QuestionId { get; set; }

    public string Key { get; set; }

    public string AddlInfo { get; set; }

    public string ImgUrl { get; set; }

    public bool IsSupplemental { get; set; }

    public int Sort { get; set; }

    public virtual Question Question { get; set; }
}