// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Maxi.Citizenship.Models;

public partial class Question
{
    public short Id { get; set; }

    public DateTimeOffset CreatedOn { get; set; }

    public Guid CreatedBy { get; set; }

    public DateTimeOffset LastModifiedOn { get; set; }

    public Guid LastModifiedBy { get; set; }

    public string Prompt { get; set; }

    public string ImageUrl { get; set; }

    public short QuestionSubCategoryId { get; set; }

    public short QuestionTypeId { get; set; }

    public bool HasAsterisk { get; set; }

    public virtual ICollection<Answer> Answers { get; } = new List<Answer>();

    public virtual ICollection<QuestionOption> QuestionOptions { get; } = new List<QuestionOption>();

    public virtual QuestionSubCategory QuestionSubCategory { get; set; }

    public virtual QuestionType QuestionType { get; set; }
}